"""empty message

Revision ID: 444353fcf9c8
Revises: d3a1b49d12ce
Create Date: 2023-08-31 14:29:45.427590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444353fcf9c8'
down_revision = 'd3a1b49d12ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_of_rooms', sa.String(), nullable=True))

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hotel_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_rooms_hotel_id_hotels'), 'hotels', ['hotel_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rooms_hotel_id_hotels'), type_='foreignkey')
        batch_op.drop_column('hotel_id')

    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_column('num_of_rooms')

    # ### end Alembic commands ###
